branch-defaults:
  default:
    environment: classmates-dev
    group_suffix: null
global:
  application_name: classmates
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: null
  sc: null
